use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"

server:
  secret_key: "maveric_secret_9834572345"
  limiter: false
  image_proxy: true
  public_instance: true
  http_protocol_version: "1.1"

ui:
  default_locale: "en"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0

enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL remover'
